### PR TITLE
Change SineWave::new() to take a float.

### PR DESCRIPTION
**Pull request by nwmahoney**
It was immediately casting it to a float anyway.

### CODE REVIEW

**Comment by aromeronavia** [comment]
I also thought this would have been a better interface for this implementation, although I don't know if the maintainers would like to approve this breaking change (as the compiler will suddenly stop working for people using the i32 implementation).

**Comment by est31** [comment]
Yeah I'm generally in favour of this PR, but it can't be merged until a new semver version of rodio due to the issue you pointed out. So it has to wait.

**Comment by nwmahoney** [comment]
Waiting for a new semver version seems right to me. Do you have an idea of when a new version including this change might be released?

**Comment by est31** [comment]
IDK there are tons of users of rodio and inconveniencing them to do a semver update requires an important reason. If there's some bigger change than just the type change it might make sense to do a semver breaking update.

**Comment by Rdna123** [comment]
Since SineWave only has two variables, the inner valuables of it could be made public without doing a semver breaking update

**Comment by est31** [comment]
I think exposing a different constructor that takes a float is a better idea. Then in a future semver incompatible upgrade, one can change new to use the new constructor.

**Comment by est31** [comment]
That being said, there are good arguments in #408 for why a major semver bump should be done. So I'll merge this.

**Pull request merged**
