### PR TITLE
Added 32-bit signed int WAV decoding. Fixes #344.

### LINKED ISSUE #344: panic 'Unimplemented wav spec: Int, 32' with a 32-bit float wav
I tried running this code based off of the basic example, where `resources/sound.wav` pointed to [this wav file](https://github.com/raysan5/raylib/blob/6e79476650321cd08c6814a304887d378b54799f/examples/audio/resources/sound.wav).
```rust
use std::io::BufReader;

fn main() {
    let (_stream, stream_handle) = rodio::OutputStream::try_default().unwrap();

    let file = std::fs::File::open("resources/sound.wav").unwrap();
    let beep2 = stream_handle.play_once(BufReader::new(file)).unwrap();
    beep2.set_volume(0.3);
    beep2.detach();

    loop {}
}
```

I got no sound and instead got this panic message:
```
thread '<unnamed>' panicked at 'Unimplemented wav spec: Int, 32', C:\Users\Ryan\.cargo\registry\src\github.com-1ecc6299
db9ec823\rodio-0.13.0\src\decoder\wav.rs:80:49
```

<details>
<summary> with RUST_BACKTRACE='full' </summary>

```
thread '<unnamed>' panicked at 'Unimplemented wav spec: Int, 32', C:\Users\Ryan\.cargo\registry\src\github.com-1ecc6299
db9ec823\rodio-0.13.0\src\decoder\wav.rs:80:49
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\..\..\backtrace\src\
backtrace\dbghelp.rs:98
   1:     0x7ff776f328a9 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\..\..\backtrace\src\
backtrace\mod.rs:66
   2:     0x7ff776f328a9 - std::sys_common::backtrace::_print_fmt
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\sys_common\backtrace
.rs:79
   3:     0x7ff776f328a9 - std::sys_common::backtrace::_print::{{impl}}::fmt
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\sys_common\backtrace
.rs:58
   4:     0x7ff776f40d4b - core::fmt::write
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\core\src\fmt\mod.rs:1080
   5:     0x7ff776f305a8 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\io\mod.rs:1516
   6:     0x7ff776f35374 - std::sys_common::backtrace::_print
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\sys_common\backtrace
.rs:61
   7:     0x7ff776f35374 - std::sys_common::backtrace::print
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\sys_common\backtrace
.rs:48
   8:     0x7ff776f35374 - std::panicking::default_hook::{{closure}}
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:208
   9:     0x7ff776f34f58 - std::panicking::default_hook
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:227
  10:     0x7ff776f35c2f - std::panicking::rust_panic_with_hook
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:577
  11:     0x7ff776f35795 - std::panicking::begin_panic_handler::{{closure}}
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:484
  12:     0x7ff776f3318f - std::sys_common::backtrace::__rust_end_short_backtrace<closure-0,!>
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\sys_common\backtrace
.rs:153
  13:     0x7ff776f35749 - std::panicking::begin_panic_handler
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:483
  14:     0x7ff776f356fc - std::panicking::begin_panic_fmt
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\panicking.rs:437
  15:     0x7ff776ef8824 - <std::io::buffered::BufReader<R> as std::io::Seek>::seek::h5cfe218e7d25e0e1
  16:     0x7ff776ed23bd - <rodio::conversions::sample_rate::SampleRateConverter<I> as core::iter::traits::iterator::It
erator>::next::h05f852c40a4f5279
  17:     0x7ff776ef3865 - claxon::metadata::read_vorbis_comment_block::h5774ab5144b6c79a
  18:     0x7ff776f04012 - <std::sys_common::poison::PoisonError<T> as core::fmt::Debug>::fmt::h23677a8ff28ec2fc
  19:     0x7ff776f03ab6 - <&T as core::fmt::Debug>::fmt::hc46ffb7dc4c85aab
  20:     0x7ff776f23a43 - cpal::host::wasapi::stream::run_output::hdae5b78e71174a04
  21:     0x7ff776f02863 - std::sys_common::backtrace::__rust_begin_short_backtrace::hd233dbd72adf7ea4
  22:     0x7ff776efbfb4 - <&T as core::fmt::Debug>::fmt::h62bca03576b08e24
  23:     0x7ff776f37cd7 - alloc::boxed::{{impl}}::call_once
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\alloc\src\boxed.rs:1042
  24:     0x7ff776f37cd7 - alloc::boxed::{{impl}}::call_once
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\library\alloc\src\boxed.rs:1042
  25:     0x7ff776f37cd7 - std::sys::windows::thread::{{impl}}::new::thread_start
                               at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4\/library\std\src\sys\windows\thread.r
s:56
  26:     0x7ffb0fba7c24 - BaseThreadInitThunk
  27:     0x7ffb1122d4d1 - RtlUserThreadStart
```

</details>

When I opened that `sound.wav` file up in Audacity, it said it was a 32-bit *float* wav file, and it was able to play it. I then tried re-encoding the file as a 24-bit wav, and that played correctly, as expected, when I changed the path in the above source code to reference that file.

So it seems like the 32-bit float wav is getting interpreted as a 32-bit int wav, which as I understand it, is not a common format. s this expected behaviour? Should 32-bit wav files be working, or are they unsupported?

Here are the two wav files mentioned, in case that helps debugging this.

[resources.zip](https://github.com/RustAudio/rodio/files/5685573/resources.zip)

### PR DESCRIPTION
**Pull request by orlp**
Title says it all.

### CODE REVIEW

**Comment by est31** [comment]
Thanks for the PR! Could you maybe try to add a smaller file? 500 kb is a bit much. Maybe try creating a third of the file in length?

**Comment by orlp** [comment]
> Thanks for the PR! Could you maybe try to add a smaller file? 500 kb is a bit much. Maybe try creating a third of the file in length?

Sure, I just re-encoded the already existing file, but with 32-bit integers that becomes bigger.

**Comment by orlp** [comment]
Frustratingly, I can't reproduce the CI failures on my machine.

**Comment by orlp** [comment]
Nope, on both my Linux and Windows machines `cargo test --features=symphonia-all --all-targets` completes without issues. No idea why it fails in the CI.

**Comment by orlp** [comment]
@est31 The CI passed this time, no idea why it failed last time I changed nothing.

**Pull request merged**
