### PR TITLE
Release 0.14.0

### PR DESCRIPTION
**Pull request by alexheretic**
This PR prepares the changelog with the current `0.14` changes.

@est31 I'd like to see a new crate release, are we waiting for anything before the next version?

### CODE REVIEW

**Comment by est31** [comment]
Thanks. Do you also want to update to 0.14 in Cargo.toml? Then it should take care of the release automatically.

**Comment by alexheretic** [comment]
> Thanks. Do you also want to update to 0.14 in Cargo.toml? Then it should take care of the release automatically.

done :+1:

**Comment by est31** [comment]
Alright I found a blocker: quickcheck is an outdated dev-dependency. It should be updated to 1.0. Do you want to do it? Preferably in a separate PR.

**Comment by alexheretic** [comment]
Ok sure, it was a bit of a pain as the tests failed with multiplication overflows after updating the version.

**Comment by alexheretic** [comment]
... now memory allocations are failing in CI :expressionless: I'll revert that back to `0.9.2` and here ends my brief relationship with quickcheck.

@est31 Do you want me to revert the version change so you can merge this and look at the quickcheck stuff later?

**Comment by est31** [comment]
Huh that's weird. Yeah we can get 0.14.0 out. Quickcheck is "only" a dev-dependency. I'll merge the PR (but squash the history) and file an issue for updating quickcheck.

**Pull request merged**
