### PR TITLE
SampleRateConverter: Fix reliance on Vec internals (see #303)

### PR DESCRIPTION
**Pull request by nbraud**
## Bugfixes

- [x] Removed use of `Vec::capacity`, instead carry the number of channels as an explicit member of the `struct SampleRateConverter`.
- [x] Fixed an underflow (leading to `panic!`) in `<u16 as Sample>::lerp`, discovered when switching to property-based tests.

## Testsuite improvements

- [x] Added a reproducing testcase for #316 (marked `#[ignore]`, pending a fix)
- [x] Switched to property-based tests (using `quickcheck`)
- [x] Generalised the tests over their input data, number of channels, and sample rates.
- [x] Generalised the sample rate multiplication and division tests over the (integer) conversion ratio.
- [x] Removed redundant tests.

### CODE REVIEW

**Comment by TonalidadeHidrica** [comment]
> @TonalidadeHidrica Yeah, I'm pretty sure it ought to be simplified a lot; what it's actually doing is just finding the 2 input samples in-between which the (current) output sample falls, and interpolating linearly between the two.
> What I was planning to do was first refactor and simplify the current implementation, fix this issue, and then look at better resampling algorithms to implement (windowed `sinc` interpolation might be a big win already, but TBH it might make more sense to go straight for band-limited interpolation)

_Originally posted by @nbraud in https://github.com/RustAudio/rodio/issues/316#issuecomment-703259661_

I thought discussion about new implementation of Sample Rate Converter should be done in here, so I quoted here.

@nbraud I think that linear of sinc interpolation seems good.  By the way, why don't we reuse an existing algorithm instead of reinventing wheels?  With a little googling I found many open-source libraries available, some of which listed [here](https://ccrma.stanford.edu/~jos/resample/Free_Resampling_Software.html).

**Comment by est31** [comment]
I won't accept PRs that replace existing Rust code with a dependency on a C library. If the specific component was rewritten in Rust I might do it, but licenses need to be compatible.

**Review by est31 — APPROVED** [review]
Thanks!

**Comment by nbraud** [comment]
> I think that linear of sinc interpolation seems good. By the way, why don't we reuse an existing algorithm instead of reinventing wheels? With a little googling I found many open-source libraries available, some of which listed [here](https://ccrma.stanford.edu/~jos/resample/Free_Resampling_Software.html).

@TonalidadeHidrica I didn't want to suggest a replacement with a C library, both for portability and ergonomics reasons (`cargo` can build or cross-build any pure-Rust dependency easily, but dealing with C dependencies can be a pain) and because it seems counter-productive to throw out all guarantees of memory safety, and it looks like @est31 agrees:

> I won't accept PRs that replace existing Rust code with a dependency on a C library. If the specific component was rewritten in Rust I might do it, but licenses need to be compatible.

... however, I looked earlier at published crates that implement audio interpolation, and found [`rubato`], which seems to be the most reasonable implementation, is MIT-licensed, and pure Rust, though it has some potential `unsafe`ty (not directly, but through its dependencies, mostly `rustfft`) : 

```
$ cargo geiger
[...]
Functions  Expressions  Impls  Traits  Methods  Dependency

0/0        0/0          0/0    0/0     0/0      ?  rubato 0.4.3
1/1        16/28        0/0    0/0     0/2      !  ├── log 0.4.11
0/0        0/0          0/0    0/0     0/0      ?  │   └── cfg-if 0.1.10
0/0        0/0          0/0    0/0     0/0      ?  ├── num 0.2.1
0/0        2/2          0/0    0/0     0/0      !  │   ├── num-bigint 0.2.6
0/0        0/0          0/0    0/0     0/0      ?  │   │   ├── num-integer 0.1.43
0/0        4/10         0/0    0/0     0/0      !  │   │   │   └── num-traits 0.2.12
0/0        4/10         0/0    0/0     0/0      !  │   │   └── num-traits 0.2.12
0/0        0/0          0/0    0/0     0/0      ?  │   ├── num-complex 0.2.4
0/0        4/10         0/0    0/0     0/0      !  │   │   └── num-traits 0.2.12
0/0        0/0          0/0    0/0     0/0      ?  │   ├── num-integer 0.1.43
0/0        0/0          0/0    0/0     0/0      ?  │   ├── num-iter 0.1.41
0/0        0/0          0/0    0/0     0/0      ?  │   │   ├── num-integer 0.1.43
0/0        4/10         0/0    0/0     0/0      !  │   │   └── num-traits 0.2.12
0/0        0/0          0/0    0/0     0/0      ?  │   ├── num-rational 0.2.4
0/0        2/2          0/0    0/0     0/0      !  │   │   ├── num-bigint 0.2.6
0/0        0/0          0/0    0/0     0/0      ?  │   │   ├── num-integer 0.1.43
0/0        4/10         0/0    0/0     0/0      !  │   │   └── num-traits 0.2.12
0/0        4/10         0/0    0/0     0/0      !  │   └── num-traits 0.2.12
0/0        0/0          0/0    0/0     0/0      ?  └── realfft 0.2.1
3/3        1362/1362    0/0    0/0     22/22    !      └── rustfft 3.0.1
0/0        0/0          0/0    0/0     0/0      ?          ├── num-complex 0.2.4
0/0        0/0          0/0    0/0     0/0      ?          ├── num-integer 0.1.43
0/0        4/10         0/0    0/0     0/0      !          ├── num-traits 0.2.12
0/0        0/0          0/0    0/0     0/0      ?          ├── strength_reduce 0.2.3
1/1        27/27        0/0    0/0     0/0      !          └── transpose 0.1.0

5/5        1411/1429    0/0    0/0     22/24  
```

@est31 Would a PR that replaces the `SampleRateConverter` with [`rubato`] be acceptable?
I might also look into submitting patches to `rustfft` to reduce the reliance on `unsafe` code.

[`rubato`]: https://crates.io/crates/rubato

**Comment by est31** [comment]
Yes, rubato sounds good, same goes for the pure-rust variant of speexdsp.

I'm not sure if rubato really needs to use all the num dependencies, and it would be great if it updated to 0.3.0. Will try to file a PR to them, but the issues are no blockers to adoption.

**Comment by est31** [comment]
The speexdsp crate to look for would probably be [speexdsp-resampler](https://docs.rs/speexdsp-resampler/). Zero dependencies, I like that. What about using that one?

**Comment by nbraud** [comment]
> The speexdsp crate to look for would probably be [speexdsp-resampler](https://docs.rs/speexdsp-resampler/). Zero dependencies, I like that. What about using that one?

If that's the one you'd insist on, sure, but I had looked at it and disregarded it because:
- there's no documentation and not much of a testsuite;
- the API seems very C-ish and error-prone: for instance, all quantities (latency, quality, sample rate, etc.) are expressed as `usize` (and we are left to guess the actual unit, since there's not documentation), instead of using `Duration` and some wrapper types;
- there was a single release ever, in February, and development seems to have stalled in June.

**Pull request merged**
