### PR TITLE
Migrate from Travis to GitHub Actions

### LINKED ISSUE #358: Move to Github actions
Turns out that rodio still uses Travis CI. One should move to Github actions.

### PR DESCRIPTION
**Pull request by CleanCut**
Resolves #358

### CODE REVIEW

**Comment by CleanCut** [comment]
@est31 Hmm...is Actions enabled for this repository?  The setting is `Settings > Actions > Actions Permissions >  Allow All Actions`

**Review by est31 — APPROVED** [review]
Thanks!

**Comment by est31** [comment]
> Hmm...is Actions enabled for this repository? The setting is Settings > Actions > Actions Permissions > Allow All Actions

It is enabled. I think github doesn't enable actions though until such a pr has been actually merged.

**Comment by CleanCut** [comment]
> I think github doesn't enable actions though until such a pr has been actually merged.

Looks like you were correct, since it's working post-merge!

**Pull request merged**
