### PR TITLE
Add Elapsed filter

### PR DESCRIPTION
**Pull request by PaddyCo**
as discussed in #192, a way to get the current elapsed time is almost required for things that are supposed to be synced to the audio (rhythm games for example)

I tried solving this by making a filter, and it appears to work pretty well!

I'm not sure this is the most idiomatic approach to the problem (I'll be honest, not super familiar with rodio, or audio in general for that matter) so if you have any suggestions or better ways to solve this, shoot :smile:

### CODE REVIEW

**Comment by TonalidadeHidrica** [comment]
I think this implementation has several problems:
* The duration updates only when next iteration of a chunk occurs.  This is a problem when we want more precise timestamp than the chunk size.
* Audio timer is not necessarily synchronized with system timer, and nor is the timing when the `next` called.   Fortunately, now that the new feature of tracking precise playing/recording position is introduced in RustAudio/cpal#397, we should make use of this instead.

**Comment by JackRedstonia** [comment]
Hello, any progress on this? Currently implementing a rhythm game using rodio and I'm hitting on this roadblock. Should I go ahead and open a PR utilising [RustAudio/cpal#397](https://github.com/RustAudio/cpal/pull/397) instead?

**Comment by TonalidadeHidrica** [comment]
@JackRedstonia Although there's no direct way to get the elapsed time info, current API already enables us getting it.  I'm developing a rhythm game too and already succeeded in implemented precise a/v sync feature.  You can see my code in my repository: TonalidadeHidrica/taiko-untitled .   By the way if you want to implement this feature you can go ahead, I think.  (I'm not an owner of this repo though)

**Comment by JackRedstonia** [comment]
@TonalidadeHidrica I looked through the code and it seems that it only works for one music track at a time, which isn't exactly what I need, I think. I also tried to add the functionality into the rodio crate for the PR but ended up nuking it all as it was too complex.

I believe I should leave this up to someone with better understanding of rodio and cpal.

**Comment by TonalidadeHidrica** [comment]
@JackRedstonia I agree that current rodio interface is, although quite easy when performing "fuzzy" playback like music player, not really cut out for precise, framewise playback, when you want to build rhythm game or DTM software for example.  That's why I only used rodio for decoding several audio data, and write to audio stream with cpal directly by myself.

Just for curiosity, what is your specific usecase you thought that my code lacks?   (Should I refrain from discussing here?)

**Comment by JackRedstonia** [comment]
@TonalidadeHidrica I'm making a game framework and I'm looking to have the ability to have any (reasonable) number of tracks playing and to be able to get their playing positions, so I'll have to change quite a lot of things to get that working. Nevertheless, the information about [RustAudio/cpal#397](https://github.com/RustAudio/cpal/pull/397) was quite useful, so much thanks for that.
Hopefully I'll come up with a decent way to get the above idea into decent code, but for now I'll experiment with another library called BASS. (not that rodio and cpal is bad of course, I just want to see what the available options are, and I'll likely not use BASS anyways due to its horrendous licensing)

**Comment by dvdsk** [comment]
This has been implemented slightly differently in rodio 0.20 as [TrackPosition](https://docs.rs/rodio/latest/rodio/source/trait.Source.html#method.track_position)

**Pull request closed without merging**
