### PR TITLE
Release 0.15.0

### PR DESCRIPTION
**Pull request by gridbugs**
Prepares the changelog for 0.15 (I've just included externally-visible changes) and bumps version number. In a separate commit I've updated the symphonia dep to 0.4 (please lmk if you'd rather that go in its own PR). Am I correct in understanding that as soon as this is merged, the release will take place automatically?

### CODE REVIEW

**Comment by est31** [comment]
Why a minor semver update and not a patch update?

**Comment by gridbugs** [comment]
Because of

> `WavDecoder`'s `total_duration` now returns the total duration of the sound rather than the remaining duration.

Think anyone is likely depending on the old behaviour and would be surprised if it changed in a patch update?

**Comment by est31** [comment]
I see, makes sense.

**Comment by est31** [comment]
Can you incorporate #399 too?

**Comment by gridbugs** [comment]
Rebased to include https://github.com/RustAudio/rodio/pull/399 and https://github.com/RustAudio/rodio/pull/394 as well and updated changelog.

**Pull request merged**
